# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-10 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('pw', 'Paperwork'), ('pr', 'Printing'), ('rf', 'Refreshments')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='comments',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='room_num',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
